import type { Engagement } from './types'

/**
 * Dados exclusivamente demonstrativos, sem relação com clientes reais.
 */
export const demoEngagements: Engagement[] = [
  {
    id: 'demo-orion',
    name: 'Sistema de gestão para crescimento',
    clientName: 'Empresa Órion (DEMO)',
    status: 'active',
    currentStage: 'execution',
    startedAt: '2026-04-06',
    updatedAt: '2026-08-21',
    demo: true,
    summary: 'Implantação demonstrativa de direção, gestão diária e melhoria do fluxo order-to-cash.',
    progressPercent: 62,
    focusPillarIds: ['purpose-direction', 'management-system', 'continuous-improvement'],
    maturity: [
      { pillarId: 'purpose-direction', level: 3, targetLevel: 4, rationale: 'Prioridades anuais definidas, ainda com desdobramento desigual.', assessedAt: '2026-05-02', evidenceIds: ['ev-orion-1'] },
      { pillarId: 'people-culture', level: 2, targetLevel: 3, rationale: 'Liderança engajada, mas coaching e competências não estão padronizados.', assessedAt: '2026-05-02', evidenceIds: ['ev-orion-2'] },
      { pillarId: 'management-system', level: 3, targetLevel: 4, rationale: 'Cadência semanal estável; gestão diária em expansão.', assessedAt: '2026-05-02', evidenceIds: ['ev-orion-1', 'ev-orion-3'] },
      { pillarId: 'continuous-improvement', level: 2, targetLevel: 4, rationale: 'A3 e kaizen iniciados em dois fluxos prioritários.', assessedAt: '2026-05-02', evidenceIds: ['ev-orion-3'] },
      { pillarId: 'innovation-growth', level: 2, targetLevel: 3, rationale: 'Voz do cliente ocorre de forma episódica.', assessedAt: '2026-05-02', evidenceIds: ['ev-orion-2'] },
    ],
    initiatives: [
      {
        id: 'init-orion-1',
        title: 'Desdobrar prioridades estratégicas',
        description: 'Conectar três objetivos anuais a donos, métricas e iniciativas por catchball.',
        status: 'in-progress',
        pillarIds: ['purpose-direction', 'management-system'],
        practiceIds: ['danaher-policy-deployment', 'abi-stretch-goals'],
        owner: 'Diretoria de Estratégia',
        startDate: '2026-05-11',
        targetDate: '2026-09-30',
        progressPercent: 70,
        metricIds: ['metric-orion-1'],
      },
      {
        id: 'init-orion-2',
        title: 'Reduzir lead time order-to-cash',
        description: 'Mapear o fluxo, atacar esperas e instalar gestão visual diária.',
        status: 'in-progress',
        pillarIds: ['management-system', 'continuous-improvement'],
        practiceIds: ['danaher-value-stream-mapping', 'danaher-a3-problem-solving', 'danaher-visual-daily-management'],
        owner: 'Gerência de Operações',
        startDate: '2026-06-01',
        targetDate: '2026-10-15',
        progressPercent: 55,
        metricIds: ['metric-orion-2', 'metric-orion-3'],
      },
    ],
    rituals: [
      { id: 'ritual-orion-1', name: 'Daily de performance O2C', purpose: 'Expor desvios e definir contramedidas no fluxo.', cadence: 'daily', owner: 'Operações', participantRoles: ['Operações', 'Financeiro', 'Comercial'], practiceIds: ['danaher-visual-daily-management'], nextOccurrence: '2026-08-25', active: true },
      { id: 'ritual-orion-2', name: 'Review de prioridades', purpose: 'Revisar resultados, dependências e decisões executivas.', cadence: 'monthly', owner: 'CEO', participantRoles: ['Diretoria', 'Donos de iniciativas'], practiceIds: ['danaher-policy-deployment'], nextOccurrence: '2026-09-03', active: true },
    ],
    metrics: [
      { id: 'metric-orion-1', name: 'Objetivos com dono e métrica', unit: '%', currentValue: 78, baselineValue: 25, targetValue: 100, direction: 'increase', status: 'on-track', period: 'ago/2026', pillarId: 'purpose-direction', practiceIds: ['danaher-policy-deployment'] },
      { id: 'metric-orion-2', name: 'Lead time order-to-cash', unit: 'dias', currentValue: 8.4, baselineValue: 12.6, targetValue: 6, direction: 'decrease', status: 'attention', period: 'ago/2026', pillarId: 'continuous-improvement', practiceIds: ['danaher-value-stream-mapping'] },
      { id: 'metric-orion-3', name: 'Desvios resolvidos no prazo', unit: '%', currentValue: 81, baselineValue: 54, targetValue: 90, direction: 'increase', status: 'on-track', period: 'ago/2026', pillarId: 'management-system', practiceIds: ['danaher-visual-daily-management'] },
    ],
    evidence: [
      { id: 'ev-orion-1', title: 'Workshop de prioridades', type: 'workshop', capturedAt: '2026-04-28', summary: 'A liderança convergiu em três resultados, mas encontrou conflitos de recursos no desdobramento.', sourceLabel: 'Workshop executivo (DEMO)', pillarIds: ['purpose-direction', 'management-system'], practiceIds: ['danaher-policy-deployment'], confidence: 'high' },
      { id: 'ev-orion-2', title: 'Entrevistas com liderança', type: 'interview', capturedAt: '2026-04-30', summary: 'Gestores relatam pouca rotina de coaching e contato irregular com clientes.', sourceLabel: '12 entrevistas (DEMO)', pillarIds: ['people-culture', 'innovation-growth'], practiceIds: ['danaher-leadership-assessment-process', 'danaher-voice-of-customer'], confidence: 'medium' },
      { id: 'ev-orion-3', title: 'Observação do fluxo O2C', type: 'observation', capturedAt: '2026-05-02', summary: 'Filas de aprovação e retrabalho concentram a maior parte do lead time.', sourceLabel: 'Gemba transacional (DEMO)', pillarIds: ['management-system', 'continuous-improvement'], practiceIds: ['danaher-transactional-process-improvement'], confidence: 'high' },
    ],
  },
  {
    id: 'demo-aurora',
    name: 'Diagnóstico de cultura e crescimento',
    clientName: 'Grupo Aurora (DEMO)',
    status: 'diagnostic',
    currentStage: 'diagnostic',
    startedAt: '2026-08-10',
    updatedAt: '2026-08-22',
    demo: true,
    summary: 'Diagnóstico demonstrativo sobre talentos, disciplina comercial e inovação.',
    progressPercent: 18,
    focusPillarIds: ['people-culture', 'innovation-growth'],
    maturity: [
      { pillarId: 'purpose-direction', level: 2, targetLevel: 4, rationale: 'Ambição declarada sem escolhas de portfólio explícitas.', assessedAt: '2026-08-20', evidenceIds: ['ev-aurora-1'] },
      { pillarId: 'people-culture', level: 2, targetLevel: 4, rationale: 'Avaliações variam entre áreas e não calibram potencial.', assessedAt: '2026-08-20', evidenceIds: ['ev-aurora-2'] },
      { pillarId: 'management-system', level: 2, targetLevel: 3, rationale: 'Indicadores existem, mas sem heartbeat comercial comum.', assessedAt: '2026-08-20', evidenceIds: ['ev-aurora-3'] },
      { pillarId: 'continuous-improvement', level: 1, targetLevel: 3, rationale: 'Ações corretivas não registram causa, dono ou verificação.', assessedAt: '2026-08-20', evidenceIds: ['ev-aurora-3'] },
      { pillarId: 'innovation-growth', level: 2, targetLevel: 4, rationale: 'Pipeline amplo sem critérios claros de scale-or-fail.', assessedAt: '2026-08-20', evidenceIds: ['ev-aurora-1'] },
    ],
    initiatives: [
      {
        id: 'init-aurora-1',
        title: 'Completar baseline diagnóstico',
        description: 'Consolidar entrevistas, métricas e evidências para priorização.',
        status: 'in-progress',
        pillarIds: ['people-culture', 'innovation-growth'],
        practiceIds: ['abi-people-review', 'danaher-voice-of-customer', 'abi-commercial-heartbeat'],
        owner: 'Sponsor do diagnóstico',
        startDate: '2026-08-10',
        targetDate: '2026-09-04',
        progressPercent: 45,
        metricIds: ['metric-aurora-1'],
      },
      {
        id: 'init-aurora-2',
        title: 'Desenhar critérios do pipeline de inovação',
        description: 'Definir hipóteses, evidências e gates adequados ao grau de incerteza.',
        status: 'planned',
        pillarIds: ['innovation-growth', 'management-system'],
        practiceIds: ['danaher-breakthrough-innovation-types', 'abi-global-innovation-process'],
        owner: 'Diretoria de Novos Negócios',
        startDate: '2026-09-07',
        targetDate: '2026-10-09',
        progressPercent: 0,
        metricIds: ['metric-aurora-2'],
      },
    ],
    rituals: [
      { id: 'ritual-aurora-1', name: 'Síntese do diagnóstico', purpose: 'Triangular fatos, lacunas e novas perguntas.', cadence: 'weekly', owner: 'Líder Alquemia', participantRoles: ['Equipe Alquemia', 'PMO do cliente'], practiceIds: ['danaher-a3-problem-solving'], nextOccurrence: '2026-08-28', active: true },
      { id: 'ritual-aurora-2', name: 'Comitê de evidências', purpose: 'Validar hipóteses antes de recomendar prioridades.', cadence: 'biweekly', owner: 'Sponsor', participantRoles: ['Sponsor', 'Diretores funcionais'], practiceIds: ['danaher-tollgate-reviews'], nextOccurrence: '2026-09-01', active: true },
    ],
    metrics: [
      { id: 'metric-aurora-1', name: 'Frentes diagnósticas concluídas', unit: '%', currentValue: 40, baselineValue: 0, targetValue: 100, direction: 'increase', status: 'on-track', period: 'ago/2026', pillarId: 'people-culture', practiceIds: ['abi-people-review'] },
      { id: 'metric-aurora-2', name: 'Projetos com critério de gate', unit: '%', currentValue: 15, baselineValue: 15, targetValue: 100, direction: 'increase', status: 'not-measured', period: 'baseline', pillarId: 'innovation-growth', practiceIds: ['abi-global-innovation-process'] },
    ],
    evidence: [
      { id: 'ev-aurora-1', title: 'Revisão do portfólio de inovação', type: 'document', capturedAt: '2026-08-18', summary: 'Projetos usam métricas financeiras semelhantes apesar de graus distintos de incerteza.', sourceLabel: 'Pipeline de inovação (DEMO)', pillarIds: ['purpose-direction', 'innovation-growth'], practiceIds: ['danaher-breakthrough-innovation-types'], confidence: 'high' },
      { id: 'ev-aurora-2', title: 'Amostra de avaliações de talentos', type: 'document', capturedAt: '2026-08-19', summary: 'Critérios de potencial e comportamento não são comparáveis entre áreas.', sourceLabel: 'Ciclo de pessoas (DEMO)', pillarIds: ['people-culture'], practiceIds: ['abi-people-review'], confidence: 'medium' },
      { id: 'ev-aurora-3', title: 'Levantamento de indicadores comerciais', type: 'metric', capturedAt: '2026-08-20', summary: 'Mercados reportam share em frequências e definições diferentes.', sourceLabel: 'Relatórios comerciais (DEMO)', pillarIds: ['management-system', 'continuous-improvement'], practiceIds: ['abi-commercial-heartbeat'], confidence: 'high' },
    ],
  },
]
