import type { AssessmentLayerApplication } from '@/lib/assessment/types'

export const layer: AssessmentLayerApplication = {
  eyebrow: 'Exclusivo · Banana Brasil',
  title: 'A Adaptive Layer™ sobre o stack da Banana Brasil.',
  lead:
    'A Banana Brasil já tem sistemas. O que falta é uma camada que os faça conversar sem redigitação, sem planilha e sem consolidação manual no meio da decisão. Consistem, VTEX, Mtrix e Power BI resolvem pedaços da operação — mas os indicadores só se juntam no fechamento mensal.',
  connects: ['Consistem ERP', 'VTEX B2B/B2C', 'Mtrix', 'Power BI', 'Datafrete', 'RD CRM', 'WhatsApp'],
  unlocks: [
    'Cockpit único em tempo real (fim do fechamento mensal)',
    'Sell-in × sell-out × giro no mesmo lugar',
    'Preço e margem sem planilha solta',
    'Ruptura e estoque visíveis no fluxo',
    'Alertas preventivos em 24h',
    'IA/LLM sobre ERP, VTEX, Mtrix e CRM',
  ],
  systems: [
    {
      id: 'consistem', name: 'Consistem (ERP)', owner: 'TI · Financeiro · Comercial',
      role: 'ERP core · pedidos, faturamento, estoque, financeiro e integrações',
      today: 'Sistema-mãe da operação transacional B2B e B2C — concentra pedido, faturamento, estoque e financeiro.',
      pain: 'O dado do ERP não flui sozinho para o BI nem para o comercial; consolidação depende de exportação manual e o status não chega em tempo real.',
      layerRole: 'Conector de eventos e consultas (pedido, faturamento, estoque, financeiro). A Layer não reescreve o ERP — expõe o que a operação precisa, com guardrails.',
    },
    {
      id: 'vtex', name: 'VTEX B2B / B2C', owner: 'Digital · Comercial',
      role: 'E-commerce oficial · canais B2B e B2C',
      today: 'Plataforma oficial de e-commerce; base da visão de "100% dos pedidos B2B digitais".',
      pain: 'Pedidos e status vivem separados do ERP e do varejo/marketplaces; a visão de canal não é unificada.',
      layerRole: 'Publica eventos de pedido, carrinho e conversão na camada — base para o cockpit e para os agentes de canal.',
    },
    {
      id: 'integrado', name: 'Integrado Sistemas', owner: 'TI',
      role: 'Middleware · integração de pedidos VTEX ↔ ERP',
      today: 'Middleware que integra os pedidos entre a VTEX e o Consistem.',
      pain: 'Integração ponto-a-ponto resolve o pedido, mas não cria verdade única nem histórico de eventos auditável.',
      layerRole: 'Coexiste. A Layer padroniza os eventos acima do middleware, com rastreabilidade e linha do tempo.',
    },
    {
      id: 'mtrix', name: 'Mtrix', owner: 'Comercial · BI',
      role: 'Sell-out · dados de distribuidores e parceiros',
      today: 'Consolida a leitura de sell-out dos distribuidores exclusivos e parceiros.',
      pain: 'Sell-out é lido em separado; cruzar com sell-in, estoque e giro é manual — a decisão só sai no fechamento.',
      layerRole: 'Eventos de sell-out entram na linha do tempo — habilitam giro, cobertura e ruptura em tempo quase real.',
    },
    {
      id: 'powerbi', name: 'Movtech + Power BI', owner: 'BI · Diretoria',
      role: 'Business Intelligence · indicadores e dashboards',
      today: 'BI, indicadores gerenciais e dashboards para a diretoria.',
      pain: 'Reflete o que foi consolidado — muitas fontes, sem tempo real, e diverge conforme a planilha de origem.',
      layerRole: 'Passa a ler de uma fonte única (a Layer). O Power BI segue como camada de visualização, sem base paralela.',
    },
    {
      id: 'datafrete', name: 'Datafrete (TMS)', owner: 'Logística',
      role: 'Gestão de fretes, transportadoras e rastreamento',
      today: 'Opera fretes, transportadoras e o rastreamento logístico do pedido.',
      pain: 'SLA de expedição/entrega e desvios chegam tarde ao comercial — o cliente cobra antes de a operação saber.',
      layerRole: 'Eventos de expedição e tracking entram na camada — habilitam alerta de SLA e o agente de logística.',
    },
    {
      id: 'bis2bis', name: 'Bis2Bis', owner: 'Digital · TI',
      role: 'Plataforma legada de e-commerce',
      today: 'Administra a plataforma legada de e-commerce.',
      pain: 'Canal legado com dados em base própria, fora do modelo unificado.',
      layerRole: 'Ponto satélite na mesma camada; eventual migração ou descontinuação avaliada sem perder histórico.',
    },
    {
      id: 'hiplatform', name: 'HI Platform', owner: 'CX',
      role: 'Atendimento ao cliente (SAC)',
      today: 'Canal de atendimento ao cliente e tickets.',
      pain: 'O contexto do pedido (status, ruptura, crédito) nem sempre chega junto do chamado.',
      layerRole: 'Enriquece o atendimento com o estado do pedido na camada — menos "vou verificar e retorno".',
    },
    {
      id: 'rdcrm', name: 'RD Station (CRM)', owner: 'Comercial · Marketing',
      role: 'CRM · leads e oportunidades comerciais',
      today: 'Gestão de leads e oportunidades comerciais.',
      pain: 'Carteira e histórico dependem do colaborador; recompra e LTV não são acionáveis — risco de conhecimento concentrado.',
      layerRole: 'CRM vira ativo estratégico: histórico e recompra ligados ao pedido real; base do agente de recompra.',
    },
    {
      id: 'ads', name: 'Google Ads / Meta Ads', owner: 'Marketing',
      role: 'Mídia · campanhas de marketing digital',
      today: 'Gestão das campanhas de mídia paga.',
      pain: 'CAC e ROAS medidos em silo, desconectados de receita e margem por canal.',
      layerRole: 'Dados de mídia entram na camada — atribuição real (CAC por canal e produto) dentro do cockpit.',
    },
    {
      id: 'gateways', name: 'Mercado Pago / Belluno', owner: 'Financeiro · Digital',
      role: 'Gateways de pagamento do e-commerce',
      today: 'Gateways de pagamento dos canais digitais.',
      pain: 'A conciliação de pagamento é operacional e manual.',
      layerRole: 'Eventos de pagamento e conciliação na camada — automação da conciliação e alerta de pedido parado.',
    },
    {
      id: 'whatsapp', name: 'WhatsApp Business', owner: 'CX · Comercial',
      role: 'Relacionamento e atendimento ao cliente',
      today: 'Canal de relacionamento e atendimento.',
      pain: 'Canal humano, sem contexto do pedido nem gatilho automático.',
      layerRole: 'Canal de saída dos alertas (24h) e das ações de recompra — a ponta dos agentes junto ao cliente.',
    },
  ],
  capabilities: [
    { id: 'integration', title: 'Integração & eventos', detail: 'Conectores dedicados publicam pedido, faturamento, estoque, sell-out (Mtrix), pagamento, expedição e mídia.' },
    { id: 'data', title: 'Dados unificados', detail: 'Uma linha do tempo por pedido, produto, cliente e canal. Sem BI paralelo e sem planilha como fonte da verdade.' },
    { id: 'apis', title: 'APIs & automação', detail: 'Quick wins (conciliação, preço, estoque, publicação, alertas) consomem a mesma API. Cada QW amplia a camada.' },
    { id: 'security', title: 'Segurança & LGPD', detail: 'Acesso, auditoria e isolamento por desenho — pré-condição para IA sobre dados reais e para a carteira pertencer à empresa.' },
  ],
  agents: [
    { id: 'command', name: 'Copiloto Executivo (Command Center)', icon: 'orchestrator', role: 'Resumo do dia, cockpit e consulta em linguagem natural ao ERP, VTEX, Mtrix e CRM.', example: '"Como foram as vendas de ontem por canal, e o que explica a variação?"', owner: 'Diretoria · Comercial' },
    { id: 'giro', name: 'Agente de Sell-in / Sell-out & Giro', icon: 'commercial', role: 'Cruza Mtrix e ERP para acompanhar giro e cobertura dos principais clientes.', example: '"Quais distribuidores estão com giro abaixo da cobertura ideal?"', owner: 'Comercial · BI' },
    { id: 'ruptura', name: 'Agente de Ruptura & Estoque', icon: 'inventory', role: 'Detecta ruptura, estoque crítico e produtos de baixo giro antes que virem problema.', example: '"Quais SKUs entram em ruptura nos próximos 7 dias?"', owner: 'Comercial · Logística' },
    { id: 'preco', name: 'Agente de Preço & Margem', icon: 'price', role: 'Substitui a planilha de simulação: versiona preço e protege a margem por canal.', example: '"Simule o impacto de −5% no preço do SKU X sobre a margem por canal."', owner: 'Comercial · Financeiro' },
    { id: 'canal', name: 'Agente de Performance de Canal', icon: 'channel', role: 'B2B, B2C, Amazon 1P e marketplaces: receita, ticket, conversão e abandono num só lugar.', example: '"Qual canal caiu em conversão esta semana e por quê?"', owner: 'Digital · Comercial' },
    { id: 'mkt', name: 'Agente de Marketing (CAC / ROAS)', icon: 'marketing', role: 'Lê Ads na camada: campanhas abaixo da meta, tráfego alto com baixa conversão, CAC elevado.', example: '"Quais campanhas estão abaixo da meta de ROAS agora?"', owner: 'Marketing' },
    { id: 'recompra', name: 'Agente de Recompra & CRM', icon: 'repurchase', role: 'Detecta clientes fora do ciclo e sugere a próxima melhor ação — ataca a concentração de receita.', example: '"Quais clientes estratégicos estão sem compra e qual abordagem usar?"', owner: 'Comercial · Marketing' },
  ],
  alerts: [
    { id: 'comercial', label: 'Comercial', tone: 'comercial', items: ['Queda nas vendas', 'Queda do ticket médio', 'Redução da conversão', 'Cliente estratégico sem compra', 'Redução da margem'] },
    { id: 'operacional', label: 'Operacional', tone: 'operacional', items: ['Produto indisponível / ruptura', 'Estoque crítico', 'Pedidos parados', 'Falha de integração ERP × VTEX', 'Erro em marketplace · atraso na expedição'] },
    { id: 'marketing', label: 'Marketing', tone: 'marketing', items: ['Campanha abaixo da meta', 'CAC elevado', 'Alto tráfego com baixa conversão', 'Queda no ROAS'] },
  ],
  alertChannel: 'WhatsApp Business + e-mail, em até 24h',
  quickWins: [
    { id: 'QW-01', stage: 'Resumo & cockpit', opportunity: 'Resumo automático das vendas do dia e insights sobre o cockpit executivo.', enabledBy: 'fonte única de vendas por canal', owner: 'Diretoria · Comercial' },
    { id: 'QW-02', stage: 'Sell-out & giro', opportunity: 'Ranking de produtos em alta/queda e leitura de giro e cobertura por cliente.', enabledBy: 'Mtrix na camada', owner: 'Comercial · BI' },
    { id: 'QW-03', stage: 'Ruptura & estoque', opportunity: 'Detecção antecipada de ruptura, estoque crítico e SKUs de baixo giro.', enabledBy: 'estoque na camada', owner: 'Comercial · Logística' },
    { id: 'QW-04', stage: 'Preço & margem', opportunity: 'Simulação de preço versionada e rentabilidade por produto e canal.', enabledBy: 'fim da planilha de preço', owner: 'Comercial · Financeiro' },
    { id: 'QW-05', stage: 'Performance de canal', opportunity: 'Análise automática de receita, ticket, conversão e abandono por canal.', enabledBy: 'canais unificados', owner: 'Digital · Comercial' },
    { id: 'QW-06', stage: 'Campanhas (CAC/ROAS)', opportunity: 'Análise automática de campanhas e alerta de desvio de CAC e ROAS.', enabledBy: 'mídia na camada', owner: 'Marketing' },
    { id: 'QW-07', stage: 'Recompra & LTV', opportunity: 'Potencial de recompra, LTV e rentabilidade por cliente com próxima melhor ação.', enabledBy: 'CRM ligado ao pedido', owner: 'Comercial · Marketing' },
    { id: 'QW-08', stage: 'Conciliação & automação', opportunity: 'Conciliação de pagamento, atualização de preço/estoque e publicação automáticas.', enabledBy: 'gateways na camada', owner: 'Financeiro · TI' },
    { id: 'QW-09', stage: 'Command Center (LLM)', opportunity: 'LLM sobre a Adaptive Layer™: consultar venda, margem, ruptura e causa em linguagem natural.', enabledBy: 'habilitado por toda a camada limpa', owner: 'CEO · Diretoria', llm: true },
  ],
}
